# Generated by Django 3.0.3 on 2020-05-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('genre', models.CharField(choices=[('1', 'Genre 1'), ('2', 'Genre 2'), ('3', 'Genre 3'), ('4', 'Genre 4'), ('5', 'Genre 5'), ('6', 'Genre 6'), ('7', 'Genre 7'), ('8', 'Genre 8'), ('9', 'Genre 9')], max_length=2)),
                ('tradeType', models.CharField(choices=[('S', 'Sale'), ('T', 'Trade'), ('G', 'Giveaway')], max_length=1)),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
